# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kluszcze/unified-memory-framework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kluszcze/unified-memory-framework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"level-zero\" \"level-zero-devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/kluszcze/unified-memory-framework/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kluszcze/unified-memory-framework/CMakeFiles /home/kluszcze/unified-memory-framework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kluszcze/unified-memory-framework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f CMakeFiles/docs.dir/build.make CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named ze_loader

# Build rule for target.
ze_loader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ze_loader
.PHONY : ze_loader

# fast build rule for target.
ze_loader/fast:
	$(MAKE) -f _deps/level-zero-loader-build/source/CMakeFiles/ze_loader.dir/build.make _deps/level-zero-loader-build/source/CMakeFiles/ze_loader.dir/build
.PHONY : ze_loader/fast

#=============================================================================
# Target rules for targets named ze_validation_layer

# Build rule for target.
ze_validation_layer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ze_validation_layer
.PHONY : ze_validation_layer

# fast build rule for target.
ze_validation_layer/fast:
	$(MAKE) -f _deps/level-zero-loader-build/source/layers/validation/CMakeFiles/ze_validation_layer.dir/build.make _deps/level-zero-loader-build/source/layers/validation/CMakeFiles/ze_validation_layer.dir/build
.PHONY : ze_validation_layer/fast

#=============================================================================
# Target rules for targets named ze_tracing_layer

# Build rule for target.
ze_tracing_layer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ze_tracing_layer
.PHONY : ze_tracing_layer

# fast build rule for target.
ze_tracing_layer/fast:
	$(MAKE) -f _deps/level-zero-loader-build/source/layers/tracing/CMakeFiles/ze_tracing_layer.dir/build.make _deps/level-zero-loader-build/source/layers/tracing/CMakeFiles/ze_tracing_layer.dir/build
.PHONY : ze_tracing_layer/fast

#=============================================================================
# Target rules for targets named ze_null

# Build rule for target.
ze_null: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ze_null
.PHONY : ze_null

# fast build rule for target.
ze_null/fast:
	$(MAKE) -f _deps/level-zero-loader-build/source/drivers/null/CMakeFiles/ze_null.dir/build.make _deps/level-zero-loader-build/source/drivers/null/CMakeFiles/ze_null.dir/build
.PHONY : ze_null/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f _deps/level-zero-loader-build/source/utils/CMakeFiles/utils.dir/build.make _deps/level-zero-loader-build/source/utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named zello_world

# Build rule for target.
zello_world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zello_world
.PHONY : zello_world

# fast build rule for target.
zello_world/fast:
	$(MAKE) -f _deps/level-zero-loader-build/samples/zello_world/CMakeFiles/zello_world.dir/build.make _deps/level-zero-loader-build/samples/zello_world/CMakeFiles/zello_world.dir/build
.PHONY : zello_world/fast

#=============================================================================
# Target rules for targets named umf

# Build rule for target.
umf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf
.PHONY : umf

# fast build rule for target.
umf/fast:
	$(MAKE) -f src/CMakeFiles/umf.dir/build.make src/CMakeFiles/umf.dir/build
.PHONY : umf/fast

#=============================================================================
# Target rules for targets named coarse

# Build rule for target.
coarse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coarse
.PHONY : coarse

# fast build rule for target.
coarse/fast:
	$(MAKE) -f src/coarse/CMakeFiles/coarse.dir/build.make src/coarse/CMakeFiles/coarse.dir/build
.PHONY : coarse/fast

#=============================================================================
# Target rules for targets named umf_test-provider_os_memory

# Build rule for target.
umf_test-provider_os_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-provider_os_memory
.PHONY : umf_test-provider_os_memory

# fast build rule for target.
umf_test-provider_os_memory/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-provider_os_memory.dir/build.make test/CMakeFiles/umf_test-provider_os_memory.dir/build
.PHONY : umf_test-provider_os_memory/fast

#=============================================================================
# Target rules for targets named umf_test-provider_os_memory_config

# Build rule for target.
umf_test-provider_os_memory_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-provider_os_memory_config
.PHONY : umf_test-provider_os_memory_config

# fast build rule for target.
umf_test-provider_os_memory_config/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-provider_os_memory_config.dir/build.make test/CMakeFiles/umf_test-provider_os_memory_config.dir/build
.PHONY : umf_test-provider_os_memory_config/fast

#=============================================================================
# Target rules for targets named umf_test-utils_common

# Build rule for target.
umf_test-utils_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-utils_common
.PHONY : umf_test-utils_common

# fast build rule for target.
umf_test-utils_common/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-utils_common.dir/build.make test/CMakeFiles/umf_test-utils_common.dir/build
.PHONY : umf_test-utils_common/fast

#=============================================================================
# Target rules for targets named umf_test-memspace_numa

# Build rule for target.
umf_test-memspace_numa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-memspace_numa
.PHONY : umf_test-memspace_numa

# fast build rule for target.
umf_test-memspace_numa/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-memspace_numa.dir/build.make test/CMakeFiles/umf_test-memspace_numa.dir/build
.PHONY : umf_test-memspace_numa/fast

#=============================================================================
# Target rules for targets named umf_test-memspace

# Build rule for target.
umf_test-memspace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-memspace
.PHONY : umf_test-memspace

# fast build rule for target.
umf_test-memspace/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-memspace.dir/build.make test/CMakeFiles/umf_test-memspace.dir/build
.PHONY : umf_test-memspace/fast

#=============================================================================
# Target rules for targets named umf_test-memtarget

# Build rule for target.
umf_test-memtarget: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-memtarget
.PHONY : umf_test-memtarget

# fast build rule for target.
umf_test-memtarget/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-memtarget.dir/build.make test/CMakeFiles/umf_test-memtarget.dir/build
.PHONY : umf_test-memtarget/fast

#=============================================================================
# Target rules for targets named umf_test-ctl

# Build rule for target.
umf_test-ctl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-ctl
.PHONY : umf_test-ctl

# fast build rule for target.
umf_test-ctl/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-ctl.dir/build.make test/CMakeFiles/umf_test-ctl.dir/build
.PHONY : umf_test-ctl/fast

#=============================================================================
# Target rules for targets named umf_test-provider_file_memory

# Build rule for target.
umf_test-provider_file_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-provider_file_memory
.PHONY : umf_test-provider_file_memory

# fast build rule for target.
umf_test-provider_file_memory/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-provider_file_memory.dir/build.make test/CMakeFiles/umf_test-provider_file_memory.dir/build
.PHONY : umf_test-provider_file_memory/fast

#=============================================================================
# Target rules for targets named umf_test-logger

# Build rule for target.
umf_test-logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-logger
.PHONY : umf_test-logger

# fast build rule for target.
umf_test-logger/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-logger.dir/build.make test/CMakeFiles/umf_test-logger.dir/build
.PHONY : umf_test-logger/fast

#=============================================================================
# Target rules for targets named umf_test-memspace_highest_capacity

# Build rule for target.
umf_test-memspace_highest_capacity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-memspace_highest_capacity
.PHONY : umf_test-memspace_highest_capacity

# fast build rule for target.
umf_test-memspace_highest_capacity/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-memspace_highest_capacity.dir/build.make test/CMakeFiles/umf_test-memspace_highest_capacity.dir/build
.PHONY : umf_test-memspace_highest_capacity/fast

#=============================================================================
# Target rules for targets named umf_test-coarse_lib

# Build rule for target.
umf_test-coarse_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-coarse_lib
.PHONY : umf_test-coarse_lib

# fast build rule for target.
umf_test-coarse_lib/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-coarse_lib.dir/build.make test/CMakeFiles/umf_test-coarse_lib.dir/build
.PHONY : umf_test-coarse_lib/fast

#=============================================================================
# Target rules for targets named umf_test-memspace_host_all

# Build rule for target.
umf_test-memspace_host_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-memspace_host_all
.PHONY : umf_test-memspace_host_all

# fast build rule for target.
umf_test-memspace_host_all/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-memspace_host_all.dir/build.make test/CMakeFiles/umf_test-memspace_host_all.dir/build
.PHONY : umf_test-memspace_host_all/fast

#=============================================================================
# Target rules for targets named umf_test-memspace_highest_bandwidth

# Build rule for target.
umf_test-memspace_highest_bandwidth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-memspace_highest_bandwidth
.PHONY : umf_test-memspace_highest_bandwidth

# fast build rule for target.
umf_test-memspace_highest_bandwidth/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-memspace_highest_bandwidth.dir/build.make test/CMakeFiles/umf_test-memspace_highest_bandwidth.dir/build
.PHONY : umf_test-memspace_highest_bandwidth/fast

#=============================================================================
# Target rules for targets named umf_test-provider_devdax_memory

# Build rule for target.
umf_test-provider_devdax_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-provider_devdax_memory
.PHONY : umf_test-provider_devdax_memory

# fast build rule for target.
umf_test-provider_devdax_memory/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-provider_devdax_memory.dir/build.make test/CMakeFiles/umf_test-provider_devdax_memory.dir/build
.PHONY : umf_test-provider_devdax_memory/fast

#=============================================================================
# Target rules for targets named umf_test-provider_os_memory_multiple_numa_nodes

# Build rule for target.
umf_test-provider_os_memory_multiple_numa_nodes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-provider_os_memory_multiple_numa_nodes
.PHONY : umf_test-provider_os_memory_multiple_numa_nodes

# fast build rule for target.
umf_test-provider_os_memory_multiple_numa_nodes/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-provider_os_memory_multiple_numa_nodes.dir/build.make test/CMakeFiles/umf_test-provider_os_memory_multiple_numa_nodes.dir/build
.PHONY : umf_test-provider_os_memory_multiple_numa_nodes/fast

#=============================================================================
# Target rules for targets named umf_test-memoryPool

# Build rule for target.
umf_test-memoryPool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-memoryPool
.PHONY : umf_test-memoryPool

# fast build rule for target.
umf_test-memoryPool/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-memoryPool.dir/build.make test/CMakeFiles/umf_test-memoryPool.dir/build
.PHONY : umf_test-memoryPool/fast

#=============================================================================
# Target rules for targets named umf_test-base

# Build rule for target.
umf_test-base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-base
.PHONY : umf_test-base

# fast build rule for target.
umf_test-base/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-base.dir/build.make test/CMakeFiles/umf_test-base.dir/build
.PHONY : umf_test-base/fast

#=============================================================================
# Target rules for targets named umf_test-base_alloc_linear

# Build rule for target.
umf_test-base_alloc_linear: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-base_alloc_linear
.PHONY : umf_test-base_alloc_linear

# fast build rule for target.
umf_test-base_alloc_linear/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-base_alloc_linear.dir/build.make test/CMakeFiles/umf_test-base_alloc_linear.dir/build
.PHONY : umf_test-base_alloc_linear/fast

#=============================================================================
# Target rules for targets named umf_test-memspace_lowest_latency

# Build rule for target.
umf_test-memspace_lowest_latency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-memspace_lowest_latency
.PHONY : umf_test-memspace_lowest_latency

# fast build rule for target.
umf_test-memspace_lowest_latency/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-memspace_lowest_latency.dir/build.make test/CMakeFiles/umf_test-memspace_lowest_latency.dir/build
.PHONY : umf_test-memspace_lowest_latency/fast

#=============================================================================
# Target rules for targets named umf_test-provider_devdax_memory_ipc

# Build rule for target.
umf_test-provider_devdax_memory_ipc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-provider_devdax_memory_ipc
.PHONY : umf_test-provider_devdax_memory_ipc

# fast build rule for target.
umf_test-provider_devdax_memory_ipc/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-provider_devdax_memory_ipc.dir/build.make test/CMakeFiles/umf_test-provider_devdax_memory_ipc.dir/build
.PHONY : umf_test-provider_devdax_memory_ipc/fast

#=============================================================================
# Target rules for targets named umf_test-utils_linux_common

# Build rule for target.
umf_test-utils_linux_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-utils_linux_common
.PHONY : umf_test-utils_linux_common

# fast build rule for target.
umf_test-utils_linux_common/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-utils_linux_common.dir/build.make test/CMakeFiles/umf_test-utils_linux_common.dir/build
.PHONY : umf_test-utils_linux_common/fast

#=============================================================================
# Target rules for targets named umf_test-provider_file_memory_ipc

# Build rule for target.
umf_test-provider_file_memory_ipc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-provider_file_memory_ipc
.PHONY : umf_test-provider_file_memory_ipc

# fast build rule for target.
umf_test-provider_file_memory_ipc/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-provider_file_memory_ipc.dir/build.make test/CMakeFiles/umf_test-provider_file_memory_ipc.dir/build
.PHONY : umf_test-provider_file_memory_ipc/fast

#=============================================================================
# Target rules for targets named umf_test-provider_fixed_memory

# Build rule for target.
umf_test-provider_fixed_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-provider_fixed_memory
.PHONY : umf_test-provider_fixed_memory

# fast build rule for target.
umf_test-provider_fixed_memory/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-provider_fixed_memory.dir/build.make test/CMakeFiles/umf_test-provider_fixed_memory.dir/build
.PHONY : umf_test-provider_fixed_memory/fast

#=============================================================================
# Target rules for targets named umf_test-mempolicy

# Build rule for target.
umf_test-mempolicy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-mempolicy
.PHONY : umf_test-mempolicy

# fast build rule for target.
umf_test-mempolicy/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-mempolicy.dir/build.make test/CMakeFiles/umf_test-mempolicy.dir/build
.PHONY : umf_test-mempolicy/fast

#=============================================================================
# Target rules for targets named umf_test-base_alloc

# Build rule for target.
umf_test-base_alloc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-base_alloc
.PHONY : umf_test-base_alloc

# fast build rule for target.
umf_test-base_alloc/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-base_alloc.dir/build.make test/CMakeFiles/umf_test-base_alloc.dir/build
.PHONY : umf_test-base_alloc/fast

#=============================================================================
# Target rules for targets named umf_test-ipc

# Build rule for target.
umf_test-ipc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-ipc
.PHONY : umf_test-ipc

# fast build rule for target.
umf_test-ipc/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-ipc.dir/build.make test/CMakeFiles/umf_test-ipc.dir/build
.PHONY : umf_test-ipc/fast

#=============================================================================
# Target rules for targets named umf_test-base_alloc_global

# Build rule for target.
umf_test-base_alloc_global: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-base_alloc_global
.PHONY : umf_test-base_alloc_global

# fast build rule for target.
umf_test-base_alloc_global/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-base_alloc_global.dir/build.make test/CMakeFiles/umf_test-base_alloc_global.dir/build
.PHONY : umf_test-base_alloc_global/fast

#=============================================================================
# Target rules for targets named umf_test-memoryProvider

# Build rule for target.
umf_test-memoryProvider: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-memoryProvider
.PHONY : umf_test-memoryProvider

# fast build rule for target.
umf_test-memoryProvider/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-memoryProvider.dir/build.make test/CMakeFiles/umf_test-memoryProvider.dir/build
.PHONY : umf_test-memoryProvider/fast

#=============================================================================
# Target rules for targets named umf_test-ipc_negative

# Build rule for target.
umf_test-ipc_negative: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test-ipc_negative
.PHONY : umf_test-ipc_negative

# fast build rule for target.
umf_test-ipc_negative/fast:
	$(MAKE) -f test/CMakeFiles/umf_test-ipc_negative.dir/build.make test/CMakeFiles/umf_test-ipc_negative.dir/build
.PHONY : umf_test-ipc_negative/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named umf_test_common

# Build rule for target.
umf_test_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_test_common
.PHONY : umf_test_common

# fast build rule for target.
umf_test_common/fast:
	$(MAKE) -f test/common/CMakeFiles/umf_test_common.dir/build.make test/common/CMakeFiles/umf_test_common.dir/build
.PHONY : umf_test_common/fast

#=============================================================================
# Target rules for targets named umf_example_memspace_hmat

# Build rule for target.
umf_example_memspace_hmat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_example_memspace_hmat
.PHONY : umf_example_memspace_hmat

# fast build rule for target.
umf_example_memspace_hmat/fast:
	$(MAKE) -f examples/CMakeFiles/umf_example_memspace_hmat.dir/build.make examples/CMakeFiles/umf_example_memspace_hmat.dir/build
.PHONY : umf_example_memspace_hmat/fast

#=============================================================================
# Target rules for targets named umf_example_memspace_numa

# Build rule for target.
umf_example_memspace_numa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_example_memspace_numa
.PHONY : umf_example_memspace_numa

# fast build rule for target.
umf_example_memspace_numa/fast:
	$(MAKE) -f examples/CMakeFiles/umf_example_memspace_numa.dir/build.make examples/CMakeFiles/umf_example_memspace_numa.dir/build
.PHONY : umf_example_memspace_numa/fast

#=============================================================================
# Target rules for targets named umf_example_basic

# Build rule for target.
umf_example_basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umf_example_basic
.PHONY : umf_example_basic

# fast build rule for target.
umf_example_basic/fast:
	$(MAKE) -f examples/CMakeFiles/umf_example_basic.dir/build.make examples/CMakeFiles/umf_example_basic.dir/build
.PHONY : umf_example_basic/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... test"
	@echo "... uninstall"
	@echo "... docs"
	@echo "... edit_cache"
	@echo "... NightlyMemCheck"
	@echo "... NightlyTest"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousUpdate"
	@echo "... NightlyUpdate"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... Experimental"
	@echo "... ContinuousCoverage"
	@echo "... Nightly"
	@echo "... NightlySubmit"
	@echo "... install"
	@echo "... NightlyStart"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalStart"
	@echo "... package"
	@echo "... NightlyBuild"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousStart"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousTest"
	@echo "... ContinuousSubmit"
	@echo "... ExperimentalConfigure"
	@echo "... Continuous"
	@echo "... ze_loader"
	@echo "... ze_validation_layer"
	@echo "... ze_tracing_layer"
	@echo "... ze_null"
	@echo "... utils"
	@echo "... zello_world"
	@echo "... umf"
	@echo "... coarse"
	@echo "... umf_test-provider_os_memory"
	@echo "... umf_test-provider_os_memory_config"
	@echo "... umf_test-utils_common"
	@echo "... umf_test-memspace_numa"
	@echo "... umf_test-memspace"
	@echo "... umf_test-memtarget"
	@echo "... umf_test-ctl"
	@echo "... umf_test-provider_file_memory"
	@echo "... umf_test-logger"
	@echo "... umf_test-memspace_highest_capacity"
	@echo "... umf_test-coarse_lib"
	@echo "... umf_test-memspace_host_all"
	@echo "... umf_test-memspace_highest_bandwidth"
	@echo "... umf_test-provider_devdax_memory"
	@echo "... umf_test-provider_os_memory_multiple_numa_nodes"
	@echo "... umf_test-memoryPool"
	@echo "... umf_test-base"
	@echo "... umf_test-base_alloc_linear"
	@echo "... umf_test-memspace_lowest_latency"
	@echo "... umf_test-provider_devdax_memory_ipc"
	@echo "... umf_test-utils_linux_common"
	@echo "... umf_test-provider_file_memory_ipc"
	@echo "... umf_test-provider_fixed_memory"
	@echo "... umf_test-mempolicy"
	@echo "... umf_test-base_alloc"
	@echo "... umf_test-ipc"
	@echo "... umf_test-base_alloc_global"
	@echo "... umf_test-memoryProvider"
	@echo "... umf_test-ipc_negative"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... umf_test_common"
	@echo "... umf_example_memspace_hmat"
	@echo "... umf_example_memspace_numa"
	@echo "... umf_example_basic"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

