# Bandit static analysis (for Python code)
name: Bandit
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  bandit:
    name: Bandit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ (matrix.os == 'ubuntu-latest' && github.repository_owner == 'oneapi-src') && 'intel-ubuntu-22.04' || matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    # Latest distros do not allow global pip installation
    - name: Install Bandit
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        echo "$PATH" >> $GITHUB_PATH
        python3 -m pip install bandit

    # Run Bandit recursively, but omit _deps directory (with 3rd party code)
    - name: Run Bandit
      run: python3 -m bandit -r . -x '/_deps/'
