name: Compute Benchmarks

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  manual:
    name: Compute Benchmarks
    uses: ./.github/workflows/reusable_benchmarks.yml
    with:
      pr_no: ${{ inputs.pr_no }}
      bench_script_params: ${{ inputs.bench_script_params }}
      upload_report: ${{ inputs.upload_report }}
