# Various non-standard tests, requiring e.g. longer run
name: Nightly

# This job is run at 04:00 UTC every day or on demand.
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: read

env:
  BUILD_DIR : "${{github.workspace}}/build"

jobs:
  Benchmarks:
    uses: ./.github/workflows/reusable_benchmarks.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      pr_no: '0'
      bench_script_params: '--save Baseline_PVC'
