# Build and push Docker images to GHCR
name: BuildDockers

on: 
  workflow_call:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs: 
  build-dockers:
    # if: github.repository == 'oneapi-src/unified-memory-framework'
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        ubuntu-version: [20.04, 22.04, 24.04]
    outputs: 
      status: ${{ job.status }}
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }} # test
      IMG: ghcr.io/bb-ur/umf-ubuntu-${{ matrix.ubuntu-version }}:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Build ubuntu-${{ matrix.ubuntu-version }} Docker image
        run: |
          docker build -f .github/docker/ubuntu-${{ matrix.ubuntu-version }}.Dockerfile -t ${{ env.IMG }} .

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@30f019fb76bb54d03ec1e716054622be511a13b2 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # test
          password: ${{ env.GHCR_TOKEN }} # test
          # registry: ghcr.io
          # username: bb-ur
          # password: ${{ secrets.BB_GHCR_TOKEN }}

      - name: Push ubuntu-${{ matrix.ubuntu-version }} Docker image
        # if: github.event_name != 'pull_request'
        run: |
          docker push ${{ env.IMG }}
