name: Docs build

on:
  workflow_call:
    inputs:
      upload:
        description: Should HTML documentation be uploaded as artifact?
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  DocsBuild:
    name: Docs build
    runs-on: ${{ github.repository_owner == 'oneapi-src' && 'intel-ubuntu-22.04' || 'ubuntu-latest' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Install doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    # Latest distros do not allow global pip installation
    - name: Install Python requirements in venv
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        echo "$PATH" >> $GITHUB_PATH
        python3 -m pip install -r third_party/requirements.txt

    - name: Build the documentation
      run: |
        cmake -B build \
          -DUMF_BUILD_LEVEL_ZERO_PROVIDER=OFF \
          -DUMF_BUILD_CUDA_PROVIDER=OFF \
          -DUMF_BUILD_TESTS=OFF \
          -DUMF_BUILD_EXAMPLES=OFF \
          -DUMF_DISABLE_HWLOC=ON
        cmake --build build --target docs

    #
    # Documentation is built. Now we want to add benchmark dashboard.
    # We only do it if inputs.upload is set, as this job is also used for testing docs build.
    #
    - name: Checkout benchmark scripts
      if: ${{ inputs.upload == true }}
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: intel/llvm
        # 07.04.2025
        # branch: sycl
        ref: 64c60c53d505260e27f1ad427fc92dd023dfedb5
        path: sc
        sparse-checkout: |
          devops/scripts/benchmarks

    - name: Move benchmark HTML files
      if: ${{ inputs.upload == true }}
      working-directory: ${{ github.workspace }}/build/docs_build/generated/html
      run: |
        mkdir performance
        mv ${{ github.workspace }}/sc/devops/scripts/benchmarks/html/* performance/

    - name: Replace config.js
      if: ${{ inputs.upload == true }}
      working-directory: ${{ github.workspace }}/build/docs_build/generated/html
      run: |
        cat << 'EOF' > ./performance/config.js
        remoteDataUrl = 'https://raw.githubusercontent.com/oneapi-src/unified-memory-framework/refs/heads/benchmark-results/data.json';
        defaultCompareNames = ["Baseline_PVC"];
        EOF

    - name: Upload artifact
      if: ${{ inputs.upload == true }}
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      with:
        path: build/docs_build/generated/html
