# Runs linter for Docker files
name: Trivy

on: workflow_call

permissions:
  contents: read
  security-events: read

jobs:
  trivy:
    name: Trivy
    runs-on: ${{ github.repository_owner == 'oneapi-src' && 'intel-ubuntu-22.04' || 'ubuntu-latest' }}
    permissions:
      security-events: write

    steps:
      - name: Clone the git repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Run Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: 1  # Fail if issue found
          # file with suppressions: .trivyignore (in root dir)

      - name: Print report and trivyignore file
        run: |
          echo "### Trivy ignore content:"
          cat .trivyignore
          echo "### Trivy report:"
          cat trivy-results.sarif

      - name: Upload results
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: 'trivy-results.sarif'
