# This workflow builds and tests providers using GPU memory. It requires properly
# labelled self-hosted runners on systems with the correct GPU and drivers.
#
# It starts jobs for both Windows and Linux runners - it's only a thin wrapper for
# the OS-specific workflows. It's better to call them twice here, instead of
# duplicating two workflow calls in the PR/push workflow, for each tested device.
#
name: GPU

on:
  workflow_call:
    inputs:
      provider:
        description: Provider name
        type: string
        required: true
      runner:
        description: Runner name (without 'DSS-' prefix)
        type: string
        required: true
      shared_lib:
        description: A list of options for building shared library
        type: string
        default: "['ON', 'OFF']"

permissions:
  contents: read

jobs:
  win:
    # run only on upstream; forks will not have the HW
    # if: github.repository == 'oneapi-src/unified-memory-framework'
    if: false
    uses: ./.github/workflows/reusable_gpu_win.yml
    with:
      provider: ${{ inputs.provider }}
      runner: ${{ inputs.runner }}
      shared_lib: ${{ inputs.shared_lib }}
  lin:
    # run only on upstream; forks will not have the HW
    if: github.repository == 'oneapi-src/unified-memory-framework'
    uses: ./.github/workflows/reusable_gpu_lin.yml
    with:
      provider: ${{ inputs.provider }}
      runner: ${{ inputs.runner }}
      shared_lib: ${{ inputs.shared_lib }}
    secrets: inherit
