# Test FetchContent of UMF on Linux and Windows (on Windows with the 'Ninja' and 'NMake Makefiles' generators)
name: FetchContent

on: workflow_call

permissions:
  contents: read
  packages: read

env:
  WORK_DIR : "${{github.workspace}}/examples/fetch_content"
  BUILD_DIR : "${{github.workspace}}/examples/fetch_content/build"

jobs:
  Linux-FetchContent:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bb-ur/umf-${{ matrix.os }}:latest
      options: --user test_user --cap-add=SYS_NICE --cap-add=SYS_PTRACE
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'ubuntu-24.04']
        build_type: [Debug, Release]
    name: FetchContent-Linux (${{matrix.os}}, build_type=${{matrix.build_type}})

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Configure the fetch_content example
      working-directory: ${{env.WORK_DIR}}
      # Fetch_Content the UMF code from the current repository (-DUMF_REPO="${{github.workspace}}")
      run: >
        cmake
        -B ${{env.BUILD_DIR}}
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DUMF_REPO="${{github.workspace}}"

    - name: Build the fetch_content example
      working-directory: ${{env.WORK_DIR}}
      run: cmake --build ${{env.BUILD_DIR}} --config ${{matrix.build_type}} -j $(nproc)

    - name: Run the fetch_content example
      working-directory: ${{env.BUILD_DIR}}
      run: ./umf_example_fetch_content

  # Build and test the fetch_content example with different CMake generators on Windows
  Windows-FetchContent:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        generator: ['Ninja', 'NMake Makefiles']
    name: FetchContent-Windows (generator=${{matrix.generator}}, build_type=${{matrix.build_type}})
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Set VCPKG_PATH
      run: echo "VCPKG_PATH=${{env.BUILD_DIR}}/vcpkg/packages/hwloc_x64-windows;${{env.BUILD_DIR}}/vcpkg/packages/tbb_x64-windows;${{env.BUILD_DIR}}/vcpkg/packages/jemalloc_x64-windows" >> $env:GITHUB_ENV

    - name: Initialize vcpkg
      uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5
      env: 
        VCPKG_PATH: ${{env.VCPKG_PATH}}
      with:
        vcpkgGitCommitId: ea2a964f9303270322cf3f2d51c265ba146c422d # 1.04.2025
        vcpkgDirectory: ${{env.BUILD_DIR}}/vcpkg
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Install dependencies
      run: vcpkg install --triplet x64-windows

    - name: Install Ninja
      if: matrix.generator == 'Ninja'
      uses: seanmiddleditch/gha-setup-ninja@3b1f8f94a2f8254bd26914c4ab9474d4f0015f67 # v6

    - name: Configure MSVC environment
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

    - name: Configure the fetch_content example
      working-directory: ${{env.WORK_DIR}}
      # Fetch_Content the UMF code from the current repository (-DUMF_REPO="${{github.workspace}}")
      run: >
        cmake
        -B ${{env.BUILD_DIR}}
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DCMAKE_PREFIX_PATH="${{env.VCPKG_PATH}}"
        -DUMF_REPO=${{github.workspace}}
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_CXX_COMPILER=cl
        -G "${{matrix.generator}}"

    - name: Build the fetch_content example
      working-directory: ${{env.WORK_DIR}}
      shell: cmd
      run: cmake --build ${{env.BUILD_DIR}} --config ${{matrix.build_type}} -j %NUMBER_OF_PROCESSORS%

    - name: Run the fetch_content example
      shell: cmd
      working-directory: ${{env.BUILD_DIR}}
      run: dir .\umf_example_fetch_content.exe
